/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption
{
    /**
     * check if GN_FEATURE_CHANGE_BRIGHTNESS_MODE is turned on or not
     */
    public static final boolean GN_FEATURE_CHANGE_BRIGHTNESS_MODE = true;
    /**
     * check if GN_FEATURE_SMART_POWERSAVER is turned on or not
     */
    public static final boolean GN_FEATURE_SMART_POWERSAVER = true;
    /**
     * check if GN_FEATURE_2_1_3 is turned on or not
     */
    public static final boolean GN_FEATURE_2_1_3 = true;
    /**
     * check if GN_FEATURE_ROOT_CHECK is turned on or not
     */
    public static final boolean GN_FEATURE_ROOT_CHECK = false;
}
